name: attendance_portal
description: "Attendance Portal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  path_provider: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/college_campus.jpg
    - assets/images/nrcm_logo.jpeg