// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMH49RUbefPnY7I80-5mW4LQPQoXzqBM',
    appId: '1:1057002571007:web:2c446919aa899a0761f8ca',
    messagingSenderId: '1057002571007',
    projectId: 'nrcm-attendance',
    authDomain: 'nrcm-attendance.firebaseapp.com',
    storageBucket: 'nrcm-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPcTCM5r7pMPd4ZcITejg_5aWc8LbUp4',
    appId: '1:1057002571007:android:73411eb026a941b861f8ca',
    messagingSenderId: '1057002571007',
    projectId: 'nrcm-attendance',
    storageBucket: 'nrcm-attendance.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDREtilfIbsEdACRtIrYH13rdM26Iu1c',
    appId: '1:1057002571007:ios:02acc54cde16278661f8ca',
    messagingSenderId: '1057002571007',
    projectId: 'nrcm-attendance',
    storageBucket: 'nrcm-attendance.firebasestorage.app',
    iosBundleId: 'com.example.attendancePortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMH49RUbefPnY7I80-5mW4LQPQoXzqBM',
    appId: '1:1057002571007:web:fe9e502d88a3097a61f8ca',
    messagingSenderId: '1057002571007',
    projectId: 'nrcm-attendance',
    authDomain: 'nrcm-attendance.firebaseapp.com',
    storageBucket: 'nrcm-attendance.firebasestorage.app',
  );
}
